# Here, the pretrained embedding model trained with train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml
# is downloaded from the speechbrain HuggingFace repository.
# However, a local path pointing to a directory containing your checkpoints may also be specified
# instead (see pretrainer below)
pretrain_path: /data/results/ecapa_tdnn/1986/save/CKPT+2021-07-18+17-42-56+00

# csv files
# train_data: !ref <save_folder>/train.csv
# enrol_data: !ref <save_folder>/enrol.csv
# test_data: !ref <save_folder>/test.csv

batch_size: 4
score_norm: 's-norm' # z-norm t-norm s-norm none
cohort_size: 2000 # amount of imposter utterances in normalization cohort 20000
n_train_snts: 40000 # used for normalization stats 400000
